/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.
*/
#include <stdio.h>
#include <string.h>
int Index(char x);
char findTheDifference(char* s, char* t);
int main(){
    char* s = "abdc";
    char* t = "bacdf";
    char r = findTheDifference(s, t);
    printf("%c\n", r);
    return 0;
}

int Index(char x){
    return x-'a';
}

char findTheDifference(char* s, char* t){
//总体思路：记录s和t中，各个字符出现的频次，频次不同的那个就是了
    int map_s[26];
    int map_t[26];
    int i;
    for(i=0;i<26;i++){
        map_s[i]=0;
        map_t[i]=0;
    }//初始化

    for(i=0;i<strlen(s);i++){
        map_s[Index(s[i])]++;
        map_t[Index(t[i])]++;
    }// 记录 strlen(s) 个字符的频次

    // t 比 s 长一位，所以：
    map_t[Index(t[i])]++;

    char res;
    for(i=0;i<26;i++){
        if(map_s[i]!=map_t[i]){
            res = 'a' + i;
            break;
        }
    }
    return res;
}